---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install RabbitMQ and dependencies
  apt:
    name: "{{ rabbitmq_packages }}"
    state: present

- name: Ensure RabbitMQ service is enabled and started
  systemd:
    name: "{{ rabbitmq_service }}"
    enabled: yes
    state: started